// <auto-generated />
using Infrastructure.Repositories.Contexes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Repositories.Migrations.Wallet
{
    [DbContext(typeof(WalletContext))]
    partial class WalletContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Portfolio.Wallet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Wallet");
                });

            modelBuilder.Entity("Domain.Portfolio.Wallet", b =>
                {
                    b.OwnsOne("Domain.Portfolio.ValueObjects.Money", "Balance", b1 =>
                        {
                            b1.Property<string>("WalletId")
                                .HasColumnType("text");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric");

                            b1.HasKey("WalletId");

                            b1.ToTable("Wallet");

                            b1.WithOwner()
                                .HasForeignKey("WalletId");
                        });

                    b.OwnsMany("Domain.Portfolio.ValueObjects.ShareVolume", "Shares", b1 =>
                        {
                            b1.Property<string>("WalletId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Volume")
                                .HasColumnType("integer");

                            b1.HasKey("WalletId", "Id");

                            b1.ToTable("ShareVolume");

                            b1.WithOwner()
                                .HasForeignKey("WalletId");
                        });

                    b.Navigation("Balance")
                        .IsRequired();

                    b.Navigation("Shares");
                });
#pragma warning restore 612, 618
        }
    }
}
