services:
  configuration:
    image: ${DOCKER_REGISTRY-}configuration
    ports:
      - "8081:8081"
    build:
      context: .
      dockerfile: Configuration/Dockerfile
    networks:
      - auth
    depends_on:
      - db

  db:
    image: postgres:latest
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - auth

networks:
  auth:
    driver: bridge
