services:
  configuration:
    container_name: monolith
    image: ${DOCKER_REGISTRY-}configuration
    ports:
      - "8081:8081"
    build:
      context: .
      dockerfile: Configuration/Dockerfile
    networks:
      - auth
    depends_on:
      - db

  db:
    container_name: sql
    image: postgres:latest
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - auth
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: 'rabbitmq:3.13.7-management'
    restart: always
    ports:
      - '5672'
      - '15672'

networks:
  auth:
    driver: bridge
